---
title: "P2P Rockyshore Biodiversity Explorer"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---

```{r setup, include=FALSE}
library(flexdashboard)
library(readr)
library(reshape2)
library(leaflet)
library(ggplot2)
library(vegan)
library(plotly)
library(lubridate)
library(dplyr)

library(RColorBrewer)
palette(brewer.pal(8, "Set2"))


```

```{r dataread}
baseDataDir = "../data/rocky/ARG/"
siteDF = read_csv(file = paste0(baseDataDir, "PMAD_siteDF.csv"))
Occurrence = read_csv(file = paste0(baseDataDir, "PMAD_occurrence.csv"))

## reorder strata factor
Occurrence$strata = factor(Occurrence$strata, levels = c("lowtide", "midtide", "hightide"))


```


General Information
======================================================================

Column
-----------------------------------------------------------------------

### Locality: `r siteDF$locality[1]` 

```{r map}
## get lat lon
siteCoords = siteDF %>% dplyr::group_by(locality, site, strata) %>% 
  dplyr::summarise(lng = mean(decimalLongitude, na.rm=T), 
            lat = mean(decimalLatitude, na.rm=T))
## get total abund and cover
siteAbund = Occurrence %>% dplyr::filter(!is.na(AphiaID))  %>% 
  dplyr::group_by(locality, site, strata) %>% 
  dplyr::summarise(sumAbund = sum(abundance, na.rm=T), 
            sumCover = sum(Cover, na.rm=T), 
            richness = n())

## add abund and cover to coords
siteCoords = full_join(siteCoords, siteAbund)

## create a color palette
pal <- colorFactor(brewer.pal(3, "Set2"), domain = c("lowtide", "midtide", "hightide"))

## make leaflet map
leaflet(siteCoords) %>% addTiles() %>% 
  addCircleMarkers(label = ~paste0(site, "-", strata, " / N Taxa: ", richness), 
                   radius = ~100 * richness/sum(richness) + 4,
                   color = ~pal(strata), 
                   fillOpacity = 0.8,
                   stroke = F,
                   clusterOptions = markerClusterOptions()) %>% 
  addMiniMap(toggleDisplay = T)

```


### Number of taxa per site and stratum

```{r taxasite}
taxaquadrat = Occurrence %>% filter(scientificName!="Bare Rock", scientificName!="Without Substrate") %>% 
  group_by(site, strata, replicateID) %>% 
  summarise(taxa.n = n())
taxaquadrat$strata = factor(taxaquadrat$strata, levels = c("lowtide", "midtide", "hightide"))

pp = ggplot(taxaquadrat, aes(strata, taxa.n, fill=strata))
pp = pp + geom_boxplot() + ylab("Number of taxa per quadrat") + 
  facet_grid(~site) + 
  theme_bw(base_size = 9) + theme(legend.position = "none")


ggplotly(pp) %>% plotly::config(displayModeBar = F) 


```

### Abundance of taxa per site and stratum

```{r taxaabund}

pp = ggplot(Occurrence, aes(strata, abundance, group=strata, fill=strata))
pp = pp + geom_boxplot() + ylab("Abundance of all taxa per quadrat") + 
  facet_grid(~site) + 
  theme_bw(base_size = 9) + theme(legend.position = "none")

ggplotly(pp) %>% plotly::config(displayModeBar = F) 

```

### Average live cover per strata

```{r taxacover}
taxacover = Occurrence %>% dplyr::filter(!is.na(AphiaID)) %>% 
  dplyr::group_by(site, strata, replicateID) %>% 
  dplyr::summarise(sumcover = sum(Cover, na.rm=T))

pp = ggplot(taxacover, aes(strata, sumcover, fill=strata))
pp = pp + geom_boxplot() + ylab("% Cover of all taxa per quadrat") + 
  facet_grid(~site) + 
  theme_bw(base_size = 9) + theme(legend.position = "none")

ggplotly(pp) %>% plotly::config(displayModeBar = F) 

```


Column
-----------------------------------------------------------------------



### taxonomic rank distribution

```{r taxonrank}
library(worms)
scNames = unique(Occurrence$AphiaID)
scNames = scNames[!is.na(scNames)]

## get taxon rank from WoRMS
scNames.rank = wormsbyid(x = scNames, verbose = F)

## summarise the results
taxranks = as.data.frame(table(scNames.rank$rank))

## make a donut
p = taxranks %>% plot_ly(labels = ~Var1, values=~Freq) %>% 
  add_pie(hole=0.6) %>% 
  layout(title = ~paste0("Total number of Taxa: ", length(scNames))) 

plotly::config(p,displayModeBar = F) 



```


### Species frequency

```{r}
taxafreq = Occurrence %>% dplyr::filter(!is.na(AphiaID)) %>% 
  dplyr::group_by(site, strata, ScientificName_accepted) %>% 
  dplyr::summarise(sppfreq = n()) %>% 
  dplyr::arrange(sppfreq) %>% 
  dplyr::mutate(sppacum = cumsum(sppfreq))

pp = ggplot(taxafreq, aes(ScientificName_accepted, sppfreq, fill=strata))
pp = pp + geom_bar(stat="identity") + coord_flip() + facet_grid(~site) + 
  theme_bw(base_size = 9) + xlab("") + ylab("number of quadrats present")

ggplotly(pp) %>% plotly::config(displayModeBar = F) 

```


### Taxa list: number of quadrats where found 

```{r taxalist}
spRanks = scNames.rank[,c("AphiaID", "rank")]

## add taxon rank to occurrence table
Occurrence = full_join(Occurrence, spRanks)

taxaTable = Occurrence %>% 
  dplyr::group_by(AphiaID) %>% dplyr::filter(!is.na(AphiaID)) %>% 
  dplyr::summarise(Taxon = unique(ScientificName_accepted), 
            rank = unique(rank), 
            lowtide = sum(strata=="lowtide", na.rm=T), 
            midtide = sum(strata=="midtide", na.rm=T), 
            hightide = sum(strata=="hightide", na.rm=T))

knitr::kable(taxaTable)

```


Indicators
=======================================================


Row
-------------------------------------------------------

### %Cover Brachidontes: High tide
```{r}
brachiCover = Occurrence %>% dplyr::filter(AphiaID==138215) %>% 
  dplyr::group_by(strata) %>% 
  dplyr::summarise(cover = format(mean(Cover, na.rm=T), digits = 3))

gauge(brachiCover$cover[brachiCover$strata=="hightide"], min=0, max=100, symbol="%")

```


### %Cover Brachidontes: Mid tide
```{r}
gauge(brachiCover$cover[brachiCover$strata=="midtide"], min=0, max=100, symbol="%")

```


### %Cover Brachidontes: Low tide

```{r}
gauge(brachiCover$cover[brachiCover$strata=="lowtide"], min=0, max=100, symbol="%")

```



Row
---------------------------------------------------------------

### Cluster by Sites

```{r}
library(vegan)

## summarise per site+strata
OccurrenceSite  = Occurrence %>% dplyr::filter(!is.na(AphiaID)) %>% 
  dplyr::group_by(site, strata, AphiaID) %>% 
  dplyr::summarise(n = n())


## cast the div data
ecoMat = dcast(site+strata~AphiaID, data=OccurrenceSite, sum)


ecoMat.dist = vegdist(ecoMat[,c(-1,-2)], method = "bray")
plot(hclust(ecoMat.dist), hang=-1, labels = paste0(ecoMat$site, "-", ecoMat$strata), ylab="B-C Distance", main="", xlab="", sub="", cex=0.7)
```


Row 
----------------------------------------------------------------

### High tide


```{r}
## filter by strata
Occurrence.strata = Occurrence %>% filter(strata=="hightide", !is.na(AphiaID))

## do it by site
siteNames = unique(Occurrence.strata$site)

## empty DF for results
sppAccum = data.frame(site = character(),
                      strata = character(),
                      ncuad = numeric(),
                      richness = numeric(), 
                      sd = numeric())

for (i in 1:length(siteNames)){
  ecoMat = dcast(eventID~AphiaID, data=subset(Occurrence.strata, site==siteNames[i]), 
                 value.var = "AphiaID", length)
  sppcurve = specaccum(ecoMat[,-1], method = "random")
  sppAccum = rbind(sppAccum, 
                   data.frame(site = rep(siteNames[i], length(sppcurve$sites)),
                              ncuad = sppcurve$sites, 
                              richness = sppcurve$richness,
                              sd = sppcurve$sd))
}

## make the plot
pp = ggplot(sppAccum, aes(ncuad, richness, colour=site, fill=site))
pp + geom_ribbon(aes(ymin=richness-sd, ymax=richness+sd), alpha=0.3) + geom_line() + geom_point() + 
  theme_bw(base_size = 10) + xlab("Number of samples") + ylab("Accumulated number of Spp")

```


### Mid tide

```{r}
## filter by strata
Occurrence.strata = Occurrence %>% filter(strata=="midtide", !is.na(AphiaID))

## do it by site
siteNames = unique(Occurrence.strata$site)

## empty DF for results
sppAccum = data.frame(site = character(),
                      strata = character(),
                      ncuad = numeric(),
                      richness = numeric(), 
                      sd = numeric())

for (i in 1:length(siteNames)){
  ecoMat = dcast(eventID~AphiaID, data=subset(Occurrence.strata, site==siteNames[i]), 
                 value.var = "AphiaID", length)
  sppcurve = specaccum(ecoMat[,-1], method = "random")
  sppAccum = rbind(sppAccum, 
                   data.frame(site = rep(siteNames[i], length(sppcurve$sites)),
                              ncuad = sppcurve$sites, 
                              richness = sppcurve$richness,
                              sd = sppcurve$sd))
}

## make the plot
pp = ggplot(sppAccum, aes(ncuad, richness, colour=site, fill=site))
pp + geom_ribbon(aes(ymin=richness-sd, ymax=richness+sd), alpha=0.3) + geom_line() + geom_point() + 
  theme_bw(base_size = 10) + xlab("Number of samples") + ylab("Accumulated number of Spp")

```



### Low tide


```{r}
## filter by strata
Occurrence.strata = Occurrence %>% filter(strata=="lowtide", !is.na(AphiaID))

## do it by site
siteNames = unique(Occurrence.strata$site)

## empty DF for results
sppAccum = data.frame(site = character(),
                      strata = character(),
                      ncuad = numeric(),
                      richness = numeric(), 
                      sd = numeric())

for (i in 1:length(siteNames)){
  ecoMat = dcast(eventID~AphiaID, data=subset(Occurrence.strata, site==siteNames[i]), 
                 value.var = "AphiaID", length)
  sppcurve = specaccum(ecoMat[,-1], method = "random")
  sppAccum = rbind(sppAccum, 
                   data.frame(site = rep(siteNames[i], length(sppcurve$sites)),
                              ncuad = sppcurve$sites, 
                              richness = sppcurve$richness,
                              sd = sppcurve$sd))
}

## make the plot
pp = ggplot(sppAccum, aes(ncuad, richness, colour=site, fill=site))
pp + geom_ribbon(aes(ymin=richness-sd, ymax=richness+sd), alpha=0.3) + geom_line() + geom_point() + 
  theme_bw(base_size = 10) + xlab("Number of samples") + ylab("Accumulated number of Spp")

```


